"""
API key validation for the MCP layer.

This is what makes a key generated by the platform meaningful when pasted into an
MCP client (Claude Desktop, Cursor, etc): every tool call is checked and metered
against the same Express-owned key_usage/request_logs rows the REST API uses.
Express remains the single source of truth for auth, quota, and billing — this
module only calls out to it (POST /internal/validate-key), it never validates or
tracks usage locally.

Auth is off by default (OPSMCP_REQUIRE_AUTH unset) so local dev, tests, and the
`run_problem.py` scripts keep working without a running Express instance or a key.
Deployments turn it on via env.

The API key is carried per-request via a ContextVar rather than a function
argument threaded through the MCP SDK's tool-call machinery. Each SSE connection
sets it once in handle_sse() (which has the raw HTTP request) before handing off
to server.run(); anyio's task group spawns each message handler with a snapshot of
that context, so every call_tool() invocation for that connection sees the same
key without touching MCP SDK internals. stdio has exactly one connection per
process, so main() sets it once at startup from OPSMCP_API_KEY.
"""

import os
import contextvars

import httpx


EXPRESS_INTERNAL_URL = os.environ.get("EXPRESS_INTERNAL_URL", "http://localhost:8080")
INTERNAL_API_SECRET = os.environ.get("INTERNAL_API_SECRET", "")
REQUIRE_API_KEY = os.environ.get("OPSMCP_REQUIRE_AUTH", "false").lower() in ("1", "true", "yes")

_api_key_ctx: contextvars.ContextVar[str | None] = contextvars.ContextVar("opsmcp_api_key", default=None)


class AuthError(Exception):
    """Raised when a tool call cannot proceed: missing/invalid/inactive key, or quota exceeded."""

    def __init__(self, message: str, code: str = "unauthorized"):
        super().__init__(message)
        self.code = code


def set_api_key(key: str | None) -> contextvars.Token:
    return _api_key_ctx.set(key)


def reset_api_key(token: contextvars.Token) -> None:
    _api_key_ctx.reset(token)


def get_api_key() -> str | None:
    return _api_key_ctx.get()


def extract_api_key(headers: dict, query_params: dict) -> str | None:
    """Pull an API key from an inbound HTTP request. Header wins over query param."""
    auth_header = headers.get("authorization") or headers.get("Authorization")
    if auth_header and auth_header.lower().startswith("bearer "):
        return auth_header[7:].strip()

    header_key = headers.get("x-api-key") or headers.get("X-Api-Key")
    if header_key:
        return header_key.strip()

    query_key = query_params.get("apiKey")
    if query_key:
        return query_key.strip()

    return None


async def validate_and_track(tool_name: str) -> None:
    """
    Validate the current context's API key against Express and record one unit of
    usage against it. No-op when OPSMCP_REQUIRE_AUTH is not set.

    Raises AuthError on missing key, invalid/inactive key, exhausted quota, or an
    unreachable/misconfigured validation service.
    """
    if not REQUIRE_API_KEY:
        return

    api_key = get_api_key()
    if not api_key:
        raise AuthError(
            "Missing API key. Pass it via the Authorization: Bearer header, "
            "?apiKey= query param, or the OPSMCP_API_KEY environment variable.",
            "missing_key",
        )

    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.post(
                f"{EXPRESS_INTERNAL_URL}/internal/validate-key",
                json={"apiKey": api_key, "tool": tool_name},
                headers={"X-Internal-Secret": INTERNAL_API_SECRET},
            )
    except httpx.RequestError as exc:
        raise AuthError(f"Could not reach the key validation service: {exc}", "validation_unavailable")

    if resp.status_code == 200:
        return

    if resp.status_code == 401:
        raise AuthError("Invalid API key.", "invalid_key")

    if resp.status_code == 403:
        raise AuthError("API key is inactive.", "key_inactive")

    if resp.status_code == 429:
        data = resp.json()
        raise AuthError(
            f"Daily limit reached ({data.get('dailyCount')}/{data.get('dailyLimit')}). "
            f"Resets at {data.get('resetsAt')}.",
            "quota_exceeded",
        )

    raise AuthError(f"Key validation failed (HTTP {resp.status_code}).", "validation_error")
